setwd("F:\\研究生课程\\东证期货杯\\选题2竞赛数据-20171114(1)\\竞赛数据-20171114")
library(plyr)
library(dplyr)
library(data.table)
contest_basic_train<-fread("contest_basic_train.tsv",encoding="UTF-8")
nrow(contest_basic_train)
contest_basic_train$AGENT[contest_basic_train$AGENT==""]<-NA
contest_basic_train$IS_LOCAL[contest_basic_train$IS_LOCAL==""]<-NA
contest_basic_train$EDU_LEVEL[contest_basic_train$EDU_LEVEL==""]<-NA
contest_basic_train$MARRY_STATUS[contest_basic_train$MARRY_STATUS==""]<-NA
contest_basic_train$AGENT<-as.factor(contest_basic_train$AGENT)
contest_basic_train$IS_LOCAL<-as.factor(contest_basic_train$IS_LOCAL)
contest_basic_train$WORK_PROVINCE<-as.factor(contest_basic_train$WORK_PROVINCE)
contest_basic_train$EDU_LEVEL<-as.factor(contest_basic_train$EDU_LEVEL)
contest_basic_train$MARRY_STATUS<-as.factor(contest_basic_train$MARRY_STATUS)
contest_basic_train$HAS_FUND<-as.factor(contest_basic_train$HAS_FUND)
#查看变量缺失之间的关系
contest_basic_train11<-contest_basic_train[,-c("REPORT_ID","ID_CARD","LOAN_DATE","Y")]
x<-as.data.frame(abs(is.na(contest_basic_train11)))
y<-x[which(apply(x,2,sum)>0)]
cor(y)
ncol(contest_basic_train)
nrow(contest_basic_train)
head(contest_basic_train)
str(contest_basic_train)
contest_ext_crd_hd_report<-fread("contest_ext_crd_hd_report.csv",encoding="UTF-8")
ncol(contest_ext_crd_hd_report)
nrow(contest_ext_crd_hd_report)
head(contest_ext_crd_hd_report)
str(contest_ext_crd_hd_report)
contest_ext_crd_cd_ln<-fread("contest_ext_crd_cd_ln.tsv",encoding="UTF-8")
contest_ext_crd_cd_ln$payment_cyc<-as.numeric(contest_ext_crd_cd_ln$payment_cyc)
contest_ext_crd_cd_ln$balance<-as.numeric(contest_ext_crd_cd_ln$balance)
contest_ext_crd_cd_ln$remain_payment_cyc<-as.numeric(contest_ext_crd_cd_ln$remain_payment_cyc)
contest_ext_crd_cd_ln$scheduled_payment_amount<-as.numeric(contest_ext_crd_cd_ln$scheduled_payment_amount)
contest_ext_crd_cd_ln$actual_payment_amount<-as.numeric(contest_ext_crd_cd_ln$actual_payment_amount)
contest_ext_crd_cd_ln$curr_overdue_cyc<-as.numeric(contest_ext_crd_cd_ln$curr_overdue_cyc)
contest_ext_crd_cd_ln$curr_overdue_amount<-as.numeric(contest_ext_crd_cd_ln$curr_overdue_amount)
ncol(contest_ext_crd_cd_ln)
nrow(contest_ext_crd_cd_ln)
head(contest_ext_crd_cd_ln)
str(contest_ext_crd_cd_ln)
contest_ext_crd_cd_lnd<-fread("contest_ext_crd_cd_lnd.tsv",encoding="UTF-8")
contest_ext_crd_cd_lnd$used_credit_limit_amount<-as.numeric(contest_ext_crd_cd_lnd$used_credit_limit_amount)
contest_ext_crd_cd_lnd$latest6_month_used_avg_amount<-as.numeric(contest_ext_crd_cd_lnd$latest6_month_used_avg_amount)
contest_ext_crd_cd_lnd$used_highest_amount<-as.numeric(contest_ext_crd_cd_lnd$used_highest_amount)
contest_ext_crd_cd_lnd$scheduled_payment_amount<-as.numeric(contest_ext_crd_cd_lnd$scheduled_payment_amount)
contest_ext_crd_cd_lnd$actual_payment_amount<-as.numeric(contest_ext_crd_cd_lnd$actual_payment_amount)
contest_ext_crd_cd_lnd$curr_overdue_cyc<-as.numeric(contest_ext_crd_cd_lnd$curr_overdue_cyc)
contest_ext_crd_cd_lnd$curr_overdue_amount<-as.numeric(contest_ext_crd_cd_lnd$curr_overdue_amount)
ncol(contest_ext_crd_cd_lnd)
nrow(contest_ext_crd_cd_lnd)
head(contest_ext_crd_cd_lnd)
str(contest_ext_crd_cd_lnd)

contest_ext_crd_is_creditcue<-fread("contest_ext_crd_is_creditcue.csv",encoding="UTF-8")
ncol(contest_ext_crd_is_creditcue)
nrow(contest_ext_crd_is_creditcue)
head(contest_ext_crd_is_creditcue)
str(contest_ext_crd_is_creditcue)

contest_ext_crd_is_sharedebt<-fread("contest_ext_crd_is_sharedebt.csv",encoding="UTF-8")
length(table(contest_ext_crd_is_sharedebt$REPORT_ID))
contest_ext_crd_is_sharedebt$MAX_CREDIT_LIMIT_PER_ORG[contest_ext_crd_is_sharedebt$MAX_CREDIT_LIMIT_PER_ORG==""]<-NA
contest_ext_crd_is_sharedebt$MIN_CREDIT_LIMIT_PER_ORG[contest_ext_crd_is_sharedebt$MIN_CREDIT_LIMIT_PER_ORG==""]<-NA
contest_ext_crd_is_sharedebt$BALANCE[contest_ext_crd_is_sharedebt$BALANCE==""]<-NA
contest_ext_crd_is_sharedebt$USED_CREDIT_LIMIT[contest_ext_crd_is_sharedebt$USED_CREDIT_LIMIT==""]<-NA
ncol(contest_ext_crd_is_sharedebt)
nrow(contest_ext_crd_is_sharedebt)
head(contest_ext_crd_is_sharedebt)
str(contest_ext_crd_is_sharedebt)

contest_ext_crd_is_ovdsummary<-fread("contest_ext_crd_is_ovdsummary.csv",encoding="UTF-8")
sum(table(contest_ext_crd_is_ovdsummary$HIGHEST_OA_PER_MON))
ncol(contest_ext_crd_is_ovdsummary)
nrow(contest_ext_crd_is_ovdsummary)
head(contest_ext_crd_is_ovdsummary)
str(contest_ext_crd_is_ovdsummary)

contest_ext_crd_qr_recordsmr<-fread("contest_ext_crd_qr_recordsmr.tsv",encoding="UTF-8")
ncol(contest_ext_crd_qr_recordsmr)
nrow(contest_ext_crd_qr_recordsmr)
head(contest_ext_crd_qr_recordsmr)
str(contest_ext_crd_qr_recordsmr)

contest_ext_crd_qr_recorddtlinfo<-fread("contest_ext_crd_qr_recorddtlinfo.tsv",encoding="UTF-8")
ncol(contest_ext_crd_qr_recorddtlinfo)
nrow(contest_ext_crd_qr_recorddtlinfo)
head(contest_ext_crd_qr_recorddtlinfo)
str(contest_ext_crd_qr_recorddtlinfo)

contest_ext_crd_cd_ln_spl<-fread("contest_ext_crd_cd_ln_spl.tsv",encoding="UTF-8")
ncol(contest_ext_crd_cd_ln_spl)
nrow(contest_ext_crd_cd_ln_spl)
head(contest_ext_crd_cd_ln_spl)
str(contest_ext_crd_cd_ln_spl)


contest_ext_crd_cd_lnd_ovd<-fread("contest_ext_crd_cd_lnd_ovd.csv",encoding="UTF-8")
contest_ext_crd_cd_lnd_ovd$AMOUNT[contest_ext_crd_cd_lnd_ovd$AMOUNT==""]<-NA
contest_ext_crd_cd_lnd_ovd$LAST_MONTHS[contest_ext_crd_cd_lnd_ovd$LAST_MONTHS==""]<-NA
nrow(contest_ext_crd_cd_lnd_ovd[contest_ext_crd_cd_lnd_ovd$MONTH_DW=="--            ",])
ncol(contest_ext_crd_cd_lnd_ovd)
nrow(contest_ext_crd_cd_lnd_ovd)
head(contest_ext_crd_cd_lnd_ovd)
str(contest_ext_crd_cd_lnd_ovd)

contest_fraud<-fread("contest_fraud.tsv",encoding="UTF-8")
ncol(contest_fraud)
nrow(contest_fraud)
head(contest_fraud)
str(contest_fraud)